/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AuthenticatedFormsIndexRouteImport } from './routes/_authenticated/forms.index'
import { Route as AuthenticatedFormsFormIdRouteImport } from './routes/_authenticated/forms.$formId'
import { Route as AuthenticatedFormsNewRouteImport } from './routes/_authenticated/forms.new'
import { Route as AuthenticatedReportsConversionsRouteImport } from './routes/_authenticated/reports.conversions'
import { Route as AuthenticatedReportsSubmissionsRouteImport } from './routes/_authenticated/reports.submissions'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates.index'
import { Route as AuthenticatedTemplatesTemplateIdRouteImport } from './routes/_authenticated/templates.$templateId'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFormsIndexRoute = AuthenticatedFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsFormIdRoute =
  AuthenticatedFormsFormIdRouteImport.update({
    id: '/forms/$formId',
    path: '/forms/$formId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormsNewRoute = AuthenticatedFormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsConversionsRoute =
  AuthenticatedReportsConversionsRouteImport.update({
    id: '/reports/conversions',
    path: '/reports/conversions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsSubmissionsRoute =
  AuthenticatedReportsSubmissionsRouteImport.update({
    id: '/reports/submissions',
    path: '/reports/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesTemplateIdRoute =
  AuthenticatedTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/f/$slug': typeof FSlugRoute
  '/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/forms/new': typeof AuthenticatedFormsNewRoute
  '/reports/conversions': typeof AuthenticatedReportsConversionsRoute
  '/reports/submissions': typeof AuthenticatedReportsSubmissionsRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/forms/': typeof AuthenticatedFormsIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/f/$slug': typeof FSlugRoute
  '/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/forms/new': typeof AuthenticatedFormsNewRoute
  '/reports/conversions': typeof AuthenticatedReportsConversionsRoute
  '/reports/submissions': typeof AuthenticatedReportsSubmissionsRoute
  '/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/forms': typeof AuthenticatedFormsIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/f/$slug': typeof FSlugRoute
  '/_authenticated/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/_authenticated/forms/new': typeof AuthenticatedFormsNewRoute
  '/_authenticated/reports/conversions': typeof AuthenticatedReportsConversionsRoute
  '/_authenticated/reports/submissions': typeof AuthenticatedReportsSubmissionsRoute
  '/_authenticated/templates/$templateId': typeof AuthenticatedTemplatesTemplateIdRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/_authenticated/forms/': typeof AuthenticatedFormsIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/f/$slug'
    | '/forms/$formId'
    | '/forms/new'
    | '/reports/conversions'
    | '/reports/submissions'
    | '/templates/$templateId'
    | '/templates/new'
    | '/forms/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/f/$slug'
    | '/forms/$formId'
    | '/forms/new'
    | '/reports/conversions'
    | '/reports/submissions'
    | '/templates/$templateId'
    | '/templates/new'
    | '/forms'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/auth_/callback'
    | '/f/$slug'
    | '/_authenticated/forms/$formId'
    | '/_authenticated/forms/new'
    | '/_authenticated/reports/conversions'
    | '/_authenticated/reports/submissions'
    | '/_authenticated/templates/$templateId'
    | '/_authenticated/templates/new'
    | '/_authenticated/forms/'
    | '/_authenticated/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FSlugRoute: typeof FSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forms/': {
      id: '/_authenticated/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AuthenticatedFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/$formId': {
      id: '/_authenticated/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof AuthenticatedFormsFormIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/new': {
      id: '/_authenticated/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof AuthenticatedFormsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/conversions': {
      id: '/_authenticated/reports/conversions'
      path: '/reports/conversions'
      fullPath: '/reports/conversions'
      preLoaderRoute: typeof AuthenticatedReportsConversionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/submissions': {
      id: '/_authenticated/reports/submissions'
      path: '/reports/submissions'
      fullPath: '/reports/submissions'
      preLoaderRoute: typeof AuthenticatedReportsSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$templateId': {
      id: '/_authenticated/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedFormsFormIdRoute: typeof AuthenticatedFormsFormIdRoute
  AuthenticatedFormsNewRoute: typeof AuthenticatedFormsNewRoute
  AuthenticatedReportsConversionsRoute: typeof AuthenticatedReportsConversionsRoute
  AuthenticatedReportsSubmissionsRoute: typeof AuthenticatedReportsSubmissionsRoute
  AuthenticatedTemplatesTemplateIdRoute: typeof AuthenticatedTemplatesTemplateIdRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedFormsIndexRoute: typeof AuthenticatedFormsIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedFormsFormIdRoute: AuthenticatedFormsFormIdRoute,
  AuthenticatedFormsNewRoute: AuthenticatedFormsNewRoute,
  AuthenticatedReportsConversionsRoute: AuthenticatedReportsConversionsRoute,
  AuthenticatedReportsSubmissionsRoute: AuthenticatedReportsSubmissionsRoute,
  AuthenticatedTemplatesTemplateIdRoute: AuthenticatedTemplatesTemplateIdRoute,
  AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
  AuthenticatedFormsIndexRoute: AuthenticatedFormsIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FSlugRoute: FSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
